projects:
  - name: GitPilot
    path: F:\Project\GitPilot
    group: github/zhuy1228
groups:
  - name: github/zhuy1228
    icon: github
  - name: gitee/zhuyuj
    icon: gitee
  - name: gitea
    icon: gitea
credentials:
  - platform: github
    username: zhuy1228
  - platform: gitee
    username: zhuyuj
  - platform: gitea
    base_url: http://localhost:3000
    username: "zhuyujun"
settings:
  concurrency: 6
  network_check: true
  log_level: info
