// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 应用服务，暴露给前端调用
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AbortMerge 中止合并
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function AbortMerge(path) {
    return $Call.ByID(3035150106, path);
}

/**
 * AddCredential 添加凭证
 * @param {string} platform
 * @param {string} baseURL
 * @param {string} username
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function AddCredential(platform, baseURL, username, token) {
    return $Call.ByID(1627284202, platform, baseURL, username, token);
}

/**
 * AddGroup 添加分组
 * @param {string} name
 * @param {string} icon
 * @returns {$CancellablePromise<void>}
 */
export function AddGroup(name, icon) {
    return $Call.ByID(4237035530, name, icon);
}

/**
 * AddProject 添加项目
 * @param {string} name
 * @param {string} path
 * @param {string} group
 * @returns {$CancellablePromise<void>}
 */
export function AddProject(name, path, group) {
    return $Call.ByID(2299402672, name, path, group);
}

/**
 * AddRemote 添加远程仓库
 * @param {string} path
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function AddRemote(path, name, url) {
    return $Call.ByID(3697916441, path, name, url);
}

/**
 * BatchMigrateProjects 批量迁移项目到目标平台
 * @param {string[]} projectPaths
 * @param {string} targetCredPlatform
 * @param {string} targetCredUsername
 * @param {string} description
 * @param {boolean} $private
 * @returns {$CancellablePromise<$models.MigrateResult[]>}
 */
export function BatchMigrateProjects(projectPaths, targetCredPlatform, targetCredUsername, description, $private) {
    return $Call.ByID(1641390103, projectPaths, targetCredPlatform, targetCredUsername, description, $private).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * BatchPull 批量拉取指定项目
 * @param {string[]} paths
 * @param {string} remote
 * @returns {$CancellablePromise<$models.BatchPullResult[]>}
 */
export function BatchPull(paths, remote) {
    return $Call.ByID(758996647, paths, remote).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * BatchPush 批量推送指定项目
 * @param {string[]} paths
 * @param {string} remote
 * @returns {$CancellablePromise<$models.BatchPullResult[]>}
 */
export function BatchPush(paths, remote) {
    return $Call.ByID(794082076, paths, remote).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CheckGitInstalled 检查 Git 是否已安装
 * @returns {$CancellablePromise<$models.GitStatus>}
 */
export function CheckGitInstalled() {
    return $Call.ByID(464620426).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * CheckoutRemoteBranch 检出远程分支到本地
 * @param {string} path
 * @param {string} remoteBranch
 * @returns {$CancellablePromise<void>}
 */
export function CheckoutRemoteBranch(path, remoteBranch) {
    return $Call.ByID(3682237522, path, remoteBranch);
}

/**
 * CloneProject 克隆远程仓库到本地目录，并添加到项目列表
 * @param {string} repoURL
 * @param {string} parentDir
 * @param {string} name
 * @param {string} group
 * @returns {$CancellablePromise<void>}
 */
export function CloneProject(repoURL, parentDir, name, group) {
    return $Call.ByID(2347019414, repoURL, parentDir, name, group);
}

/**
 * CommitChanges 提交已暂存的更改
 * @param {string} path
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function CommitChanges(path, message) {
    return $Call.ByID(921984546, path, message);
}

/**
 * CreateBranch 创建新分支
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function CreateBranch(path, name) {
    return $Call.ByID(1422152924, path, name);
}

/**
 * CreateTag 创建标签
 * @param {string} path
 * @param {string} name
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function CreateTag(path, name, message) {
    return $Call.ByID(4209616956, path, name, message);
}

/**
 * DeleteBranch 删除本地分支
 * @param {string} path
 * @param {string} name
 * @param {boolean} force
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBranch(path, name, force) {
    return $Call.ByID(580272035, path, name, force);
}

/**
 * DeleteRemoteBranch 删除远程分支
 * @param {string} path
 * @param {string} branch
 * @param {string} remote
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRemoteBranch(path, branch, remote) {
    return $Call.ByID(2626609049, path, branch, remote);
}

/**
 * DeleteTag 删除标签（本地+远程）
 * @param {string} path
 * @param {string} name
 * @param {string} remote
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTag(path, name, remote) {
    return $Call.ByID(873653241, path, name, remote);
}

/**
 * DiscardFiles 丢弃工作区指定文件的更改
 * @param {string} path
 * @param {string[]} files
 * @returns {$CancellablePromise<void>}
 */
export function DiscardFiles(path, files) {
    return $Call.ByID(382904301, path, files);
}

/**
 * FetchProject 拉取远程信息（指定 remote，空则 fetch --all）
 * @param {string} path
 * @param {string} remote
 * @returns {$CancellablePromise<string>}
 */
export function FetchProject(path, remote) {
    return $Call.ByID(3541106829, path, remote);
}

/**
 * GetAllProjectOverview 获取所有项目的概览状态
 * @returns {$CancellablePromise<$models.ProjectOverview[]>}
 */
export function GetAllProjectOverview() {
    return $Call.ByID(2453130151).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetAppSettings 获取应用设置
 * @returns {$CancellablePromise<config$0.Settings | null>}
 */
export function GetAppSettings() {
    return $Call.ByID(428589026).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * GetBranches 获取所有本地分支
 * @param {string} path
 * @returns {$CancellablePromise<$models.BranchInfo[]>}
 */
export function GetBranches(path) {
    return $Call.ByID(1686190192, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetCommitDiff 获取指定提交的 diff
 * @param {string} path
 * @param {string} hash
 * @returns {$CancellablePromise<string>}
 */
export function GetCommitDiff(path, hash) {
    return $Call.ByID(3678609798, path, hash);
}

/**
 * GetCommitFileDiff 获取指定提交中某个文件的 diff
 * @param {string} path
 * @param {string} hash
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetCommitFileDiff(path, hash, filePath) {
    return $Call.ByID(880053428, path, hash, filePath);
}

/**
 * GetCommitFiles 获取指定提交中变更的文件列表
 * @param {string} path
 * @param {string} hash
 * @returns {$CancellablePromise<$models.CommitFileInfo[]>}
 */
export function GetCommitFiles(path, hash) {
    return $Call.ByID(2420707876, path, hash).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetCommitLog 获取提交历史
 * @param {string} path
 * @param {number} count
 * @returns {$CancellablePromise<$models.CommitLog[]>}
 */
export function GetCommitLog(path, count) {
    return $Call.ByID(1281870789, path, count).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetConflictFileContent 获取冲突文件内容（包含冲突标记）
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetConflictFileContent(projectPath, filePath) {
    return $Call.ByID(298498517, projectPath, filePath);
}

/**
 * GetConflictFiles 获取冲突文件列表
 * @param {string} path
 * @returns {$CancellablePromise<$models.ConflictFileInfo[]>}
 */
export function GetConflictFiles(path) {
    return $Call.ByID(2446806137, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetCredentials 获取所有凭证
 * @returns {$CancellablePromise<$models.CredentialInfo[]>}
 */
export function GetCredentials() {
    return $Call.ByID(4214051290).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetFileContent 获取文件内容
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetFileContent(projectPath, filePath) {
    return $Call.ByID(3085630035, projectPath, filePath);
}

/**
 * GetFileDiff 获取文件 diff
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetFileDiff(projectPath, filePath) {
    return $Call.ByID(1694304929, projectPath, filePath);
}

/**
 * GetFileDiffStaged 获取已暂存文件的 diff
 * @param {string} projectPath
 * @param {string} filePath
 * @returns {$CancellablePromise<string>}
 */
export function GetFileDiffStaged(projectPath, filePath) {
    return $Call.ByID(2773256455, projectPath, filePath);
}

/**
 * GetGitGlobalConfig 获取 git 全局配置
 * @returns {$CancellablePromise<$models.GitConfig | null>}
 */
export function GetGitGlobalConfig() {
    return $Call.ByID(154811497).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetGroups 获取所有分组
 * @returns {$CancellablePromise<config$0.Group[]>}
 */
export function GetGroups() {
    return $Call.ByID(1600884836).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetProjectChangedFiles 获取项目变更文件列表（可能较慢）
 * @param {string} path
 * @returns {$CancellablePromise<$models.FileInfo[]>}
 */
export function GetProjectChangedFiles(path) {
    return $Call.ByID(2302591462, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetProjectProxy 获取项目代理设置（nil 表示跟随全局）
 * @param {string} path
 * @returns {$CancellablePromise<boolean | null>}
 */
export function GetProjectProxy(path) {
    return $Call.ByID(2515497911, path);
}

/**
 * GetProjectStatus 获取项目 git 状态
 * @param {string} path
 * @returns {$CancellablePromise<$models.ProjectStatus | null>}
 */
export function GetProjectStatus(path) {
    return $Call.ByID(3451089027, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * GetProjectTree 获取项目树，按分组组织
 * @returns {$CancellablePromise<$models.TreeNode[]>}
 */
export function GetProjectTree() {
    return $Call.ByID(651189689).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * GetRemoteBranches 获取远程分支列表
 * @param {string} path
 * @param {string} remote
 * @returns {$CancellablePromise<$models.BranchInfo[]>}
 */
export function GetRemoteBranches(path, remote) {
    return $Call.ByID(994796370, path, remote).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetRemoteReleases 获取指定远程仓库的 Release 列表
 * overrideToken: 前端传入的 Token，优先于凭证中的 Token
 * @param {string} projectPath
 * @param {string} remoteName
 * @param {string} overrideToken
 * @returns {$CancellablePromise<$models.ReleaseInfo[]>}
 */
export function GetRemoteReleases(projectPath, remoteName, overrideToken) {
    return $Call.ByID(280863080, projectPath, remoteName, overrideToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * GetRemotes 获取项目所有远程仓库列表
 * @param {string} path
 * @returns {$CancellablePromise<$models.RemoteItem[]>}
 */
export function GetRemotes(path) {
    return $Call.ByID(975520027, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * GetStashList 获取贮藏列表
 * @param {string} path
 * @returns {$CancellablePromise<$models.StashInfo[]>}
 */
export function GetStashList(path) {
    return $Call.ByID(1948257945, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType34($result);
    }));
}

/**
 * GetTags 获取所有标签
 * @param {string} path
 * @returns {$CancellablePromise<$models.TagInfo[]>}
 */
export function GetTags(path) {
    return $Call.ByID(3979169621, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType36($result);
    }));
}

/**
 * InstallGit 下载并安装 Git
 * installDir: 用户选择的安装目录（Windows 有效）
 * @param {string} installDir
 * @returns {$CancellablePromise<void>}
 */
export function InstallGit(installDir) {
    return $Call.ByID(1052641569, installDir);
}

/**
 * IsMerging 检查是否处于合并状态
 * @param {string} path
 * @returns {$CancellablePromise<boolean>}
 */
export function IsMerging(path) {
    return $Call.ByID(693809703, path);
}

/**
 * MergeBranch 合并指定分支到当前分支
 * @param {string} path
 * @param {string} branch
 * @returns {$CancellablePromise<string>}
 */
export function MergeBranch(path, branch) {
    return $Call.ByID(278161076, path, branch);
}

/**
 * MigrateProject 将项目迁移到目标平台
 * targetCredPlatform + targetCredUsername 用于定位目标凭证
 * repoName: 目标仓库名（空则用项目名）
 * remoteName: 新增的远程名（空则用平台名）
 * private: 是否私有仓库
 * description: 仓库描述
 * @param {string} projectPath
 * @param {string} targetCredPlatform
 * @param {string} targetCredUsername
 * @param {string} repoName
 * @param {string} remoteName
 * @param {string} description
 * @param {boolean} $private
 * @returns {$CancellablePromise<$models.MigrateResult | null>}
 */
export function MigrateProject(projectPath, targetCredPlatform, targetCredUsername, repoName, remoteName, description, $private) {
    return $Call.ByID(618007206, projectPath, targetCredPlatform, targetCredUsername, repoName, remoteName, description, $private).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * MoveProjectToGroup 移动项目到指定分组
 * @param {string} path
 * @param {string} group
 * @returns {$CancellablePromise<void>}
 */
export function MoveProjectToGroup(path, group) {
    return $Call.ByID(1699187666, path, group);
}

/**
 * OnlineMigrateCompare 对比两个平台的仓库列表
 * @param {string} srcPlatform
 * @param {string} srcBaseURL
 * @param {string} srcUsername
 * @param {string} srcToken
 * @param {string} tgtPlatform
 * @param {string} tgtBaseURL
 * @param {string} tgtUsername
 * @param {string} tgtToken
 * @returns {$CancellablePromise<$models.OnlineMigrateCompareResult | null>}
 */
export function OnlineMigrateCompare(srcPlatform, srcBaseURL, srcUsername, srcToken, tgtPlatform, tgtBaseURL, tgtUsername, tgtToken) {
    return $Call.ByID(3514758503, srcPlatform, srcBaseURL, srcUsername, srcToken, tgtPlatform, tgtBaseURL, tgtUsername, tgtToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType39($result);
    }));
}

/**
 * OnlineMigrateExecute 执行在线迁移
 * @param {string} srcPlatform
 * @param {string} srcBaseURL
 * @param {string} srcUsername
 * @param {string} srcToken
 * @param {string} tgtPlatform
 * @param {string} tgtBaseURL
 * @param {string} tgtUsername
 * @param {string} tgtToken
 * @param {string[]} repoNames
 * @param {boolean} srcUseProxy
 * @param {boolean} tgtUseProxy
 * @param {$models.MigrateOptions} opts
 * @returns {$CancellablePromise<$models.OnlineMigrateItemResult[]>}
 */
export function OnlineMigrateExecute(srcPlatform, srcBaseURL, srcUsername, srcToken, tgtPlatform, tgtBaseURL, tgtUsername, tgtToken, repoNames, srcUseProxy, tgtUseProxy, opts) {
    return $Call.ByID(357541815, srcPlatform, srcBaseURL, srcUsername, srcToken, tgtPlatform, tgtBaseURL, tgtUsername, tgtToken, repoNames, srcUseProxy, tgtUseProxy, opts).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType41($result);
    }));
}

/**
 * PullProject 拉取项目（当前分支，指定 remote）
 * @param {string} path
 * @param {string} remote
 * @returns {$CancellablePromise<string>}
 */
export function PullProject(path, remote) {
    return $Call.ByID(4145813996, path, remote);
}

/**
 * PushProject 推送项目（当前分支，指定 remote）
 * @param {string} path
 * @param {string} remote
 * @returns {$CancellablePromise<string>}
 */
export function PushProject(path, remote) {
    return $Call.ByID(3887901113, path, remote);
}

/**
 * PushTag 推送标签到远程
 * @param {string} path
 * @param {string} name
 * @param {string} remote
 * @returns {$CancellablePromise<void>}
 */
export function PushTag(path, name, remote) {
    return $Call.ByID(1424810524, path, name, remote);
}

/**
 * PushTagToAllRemotes 一键推送标签到所有远程仓库
 * @param {string} path
 * @param {string} tagName
 * @returns {$CancellablePromise<$models.PushAllResult[]>}
 */
export function PushTagToAllRemotes(path, tagName) {
    return $Call.ByID(2343581171, path, tagName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * PushToAllRemotes 一键推送到所有远程仓库（当前分支）
 * @param {string} path
 * @returns {$CancellablePromise<$models.PushAllResult[]>}
 */
export function PushToAllRemotes(path) {
    return $Call.ByID(1027392731, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType43($result);
    }));
}

/**
 * RemoveCredential 删除凭证
 * @param {string} platform
 * @param {string} username
 * @returns {$CancellablePromise<void>}
 */
export function RemoveCredential(platform, username) {
    return $Call.ByID(414538393, platform, username);
}

/**
 * RemoveGroup 删除分组（分组下的项目变为"未分组"）
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveGroup(name) {
    return $Call.ByID(3268966203, name);
}

/**
 * RemoveProject 删除项目（按路径匹配）
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function RemoveProject(path) {
    return $Call.ByID(2748109581, path);
}

/**
 * RemoveRemote 删除远程仓库
 * @param {string} path
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RemoveRemote(path, name) {
    return $Call.ByID(2915623022, path, name);
}

/**
 * ResetProject 版本回滚（git reset）
 * mode: "hard"(丢弃所有更改), "soft"(保留更改到暂存区), "mixed"(保留更改到工作区)
 * @param {string} path
 * @param {string} hash
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function ResetProject(path, hash, mode) {
    return $Call.ByID(2061148684, path, hash, mode);
}

/**
 * ResolveConflictFile 将冲突文件标记为已解决
 * @param {string} path
 * @param {string[]} files
 * @returns {$CancellablePromise<void>}
 */
export function ResolveConflictFile(path, files) {
    return $Call.ByID(1893119072, path, files);
}

/**
 * RevertCommit 撤回指定提交（生成一个反向提交）
 * @param {string} path
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function RevertCommit(path, hash) {
    return $Call.ByID(1334788539, path, hash);
}

/**
 * SaveConflictFile 保存冲突文件内容（手动解决冲突后保存）
 * @param {string} projectPath
 * @param {string} filePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveConflictFile(projectPath, filePath, content) {
    return $Call.ByID(3340289161, projectPath, filePath, content);
}

/**
 * SearchCommitLog 搜索提交历史
 * @param {string} path
 * @param {string} keyword
 * @param {string} author
 * @param {number} maxCount
 * @returns {$CancellablePromise<$models.CommitLog[]>}
 */
export function SearchCommitLog(path, keyword, author, maxCount) {
    return $Call.ByID(2874450917, path, keyword, author, maxCount).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * SelectDirectory 打开系统文件夹选择器，返回选中的路径
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory() {
    return $Call.ByID(2318416763);
}

/**
 * SelectGitInstallDir 打开文件夹选择器让用户选择 Git 安装路径
 * @returns {$CancellablePromise<string>}
 */
export function SelectGitInstallDir() {
    return $Call.ByID(2941074074);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(383695022, app);
}

/**
 * SetGitGlobalConfig 设置 git 全局配置
 * @param {string} name
 * @param {string} email
 * @returns {$CancellablePromise<void>}
 */
export function SetGitGlobalConfig(name, email) {
    return $Call.ByID(3875064981, name, email);
}

/**
 * SetProjectProxy 设置项目代理开关
 * useProxy: true=强制启用, false=强制禁用, nil(传空)=跟随全局
 * @param {string} path
 * @param {boolean | null} useProxy
 * @returns {$CancellablePromise<void>}
 */
export function SetProjectProxy(path, useProxy) {
    return $Call.ByID(4094650651, path, useProxy);
}

/**
 * StageAll 暂存所有变更文件
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function StageAll(path) {
    return $Call.ByID(2344562461, path);
}

/**
 * StageFiles 暂存指定文件
 * @param {string} path
 * @param {string[]} files
 * @returns {$CancellablePromise<void>}
 */
export function StageFiles(path, files) {
    return $Call.ByID(4064506881, path, files);
}

/**
 * StashApply 应用贮藏（不删除）
 * @param {string} path
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function StashApply(path, index) {
    return $Call.ByID(721583959, path, index);
}

/**
 * StashDrop 删除贮藏
 * @param {string} path
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function StashDrop(path, index) {
    return $Call.ByID(3821556536, path, index);
}

/**
 * StashPop 应用贮藏并删除
 * @param {string} path
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function StashPop(path, index) {
    return $Call.ByID(4117964460, path, index);
}

/**
 * StashSave 保存当前变更到贮藏
 * @param {string} path
 * @param {string} message
 * @returns {$CancellablePromise<void>}
 */
export function StashSave(path, message) {
    return $Call.ByID(1178263140, path, message);
}

/**
 * SwitchBranch 切换分支
 * @param {string} path
 * @param {string} branch
 * @returns {$CancellablePromise<void>}
 */
export function SwitchBranch(path, branch) {
    return $Call.ByID(4262224900, path, branch);
}

/**
 * SyncReleases 将源远程仓库的 Release 同步到目标远程仓库
 * 仅同步目标不存在的 Release，包括附件
 * @param {string} projectPath
 * @param {string} sourceRemote
 * @param {string} targetRemote
 * @param {string} srcOverrideToken
 * @param {string} tgtOverrideToken
 * @returns {$CancellablePromise<$models.ReleaseSyncResult[]>}
 */
export function SyncReleases(projectPath, sourceRemote, targetRemote, srcOverrideToken, tgtOverrideToken) {
    return $Call.ByID(3895607505, projectPath, sourceRemote, targetRemote, srcOverrideToken, tgtOverrideToken).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType45($result);
    }));
}

/**
 * UnstageAll 取消暂存所有文件
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function UnstageAll(path) {
    return $Call.ByID(2417621882, path);
}

/**
 * UnstageFiles 取消暂存指定文件
 * @param {string} path
 * @param {string[]} files
 * @returns {$CancellablePromise<void>}
 */
export function UnstageFiles(path, files) {
    return $Call.ByID(3546473046, path, files);
}

/**
 * UpdateAppSettings 更新应用设置
 * @param {string} logLevel
 * @returns {$CancellablePromise<void>}
 */
export function UpdateAppSettings(logLevel) {
    return $Call.ByID(718820989, logLevel);
}

/**
 * UpdateCredential 更新凭证
 * @param {string} platform
 * @param {string} username
 * @param {string} baseURL
 * @param {string} token
 * @returns {$CancellablePromise<void>}
 */
export function UpdateCredential(platform, username, baseURL, token) {
    return $Call.ByID(2448329924, platform, username, baseURL, token);
}

/**
 * UpdateGroup 修改分组
 * @param {string} oldName
 * @param {string} newName
 * @param {string} icon
 * @returns {$CancellablePromise<void>}
 */
export function UpdateGroup(oldName, newName, icon) {
    return $Call.ByID(1322206248, oldName, newName, icon);
}

// Private type creation functions
const $$createType0 = $models.MigrateResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.BatchPullResult.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.GitStatus.createFrom;
const $$createType5 = $models.ProjectOverview.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = config$0.Settings.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $models.BranchInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.CommitFileInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.CommitLog.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.ConflictFileInfo.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.CredentialInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.GitConfig.createFrom;
const $$createType20 = $Create.Nullable($$createType19);
const $$createType21 = config$0.Group.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.FileInfo.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.ProjectStatus.createFrom;
const $$createType26 = $Create.Nullable($$createType25);
const $$createType27 = $models.TreeNode.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $models.ReleaseInfo.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = $models.RemoteItem.createFrom;
const $$createType32 = $Create.Array($$createType31);
const $$createType33 = $models.StashInfo.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = $models.TagInfo.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = $Create.Nullable($$createType0);
const $$createType38 = $models.OnlineMigrateCompareResult.createFrom;
const $$createType39 = $Create.Nullable($$createType38);
const $$createType40 = $models.OnlineMigrateItemResult.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = $models.PushAllResult.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = $models.ReleaseSyncResult.createFrom;
const $$createType45 = $Create.Array($$createType44);
