// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AssetInfo Release 附件
 */
export class AssetInfo {
    /**
     * Creates a new AssetInfo instance.
     * @param {Partial<AssetInfo>} [$$source = {}] - The source object to create the AssetInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size"] = 0;
        }
        if (!("downloadUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["downloadUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AssetInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AssetInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AssetInfo(/** @type {Partial<AssetInfo>} */($$parsedSource));
    }
}

/**
 * BatchPullResult 批量 pull 结果
 */
export class BatchPullResult {
    /**
     * Creates a new BatchPullResult instance.
     * @param {Partial<BatchPullResult>} [$$source = {}] - The source object to create the BatchPullResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchPullResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchPullResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BatchPullResult(/** @type {Partial<BatchPullResult>} */($$parsedSource));
    }
}

/**
 * BranchInfo 分支信息
 */
export class BranchInfo {
    /**
     * Creates a new BranchInfo instance.
     * @param {Partial<BranchInfo>} [$$source = {}] - The source object to create the BranchInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("current" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["current"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BranchInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BranchInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BranchInfo(/** @type {Partial<BranchInfo>} */($$parsedSource));
    }
}

/**
 * CommitFileInfo 提交中的文件变更信息
 */
export class CommitFileInfo {
    /**
     * Creates a new CommitFileInfo instance.
     * @param {Partial<CommitFileInfo>} [$$source = {}] - The source object to create the CommitFileInfo.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitFileInfo(/** @type {Partial<CommitFileInfo>} */($$parsedSource));
    }
}

/**
 * CommitLog 提交记录
 */
export class CommitLog {
    /**
     * Creates a new CommitLog instance.
     * @param {Partial<CommitLog>} [$$source = {}] - The source object to create the CommitLog.
     */
    constructor($$source = {}) {
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("shortHash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["shortHash"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("pushed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pushed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitLog instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommitLog}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommitLog(/** @type {Partial<CommitLog>} */($$parsedSource));
    }
}

/**
 * ConflictFileInfo 冲突文件信息
 */
export class ConflictFileInfo {
    /**
     * Creates a new ConflictFileInfo instance.
     * @param {Partial<ConflictFileInfo>} [$$source = {}] - The source object to create the ConflictFileInfo.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConflictFileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConflictFileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConflictFileInfo(/** @type {Partial<ConflictFileInfo>} */($$parsedSource));
    }
}

/**
 * CredentialInfo 凭证信息（前端展示用）
 */
export class CredentialInfo {
    /**
     * Creates a new CredentialInfo instance.
     * @param {Partial<CredentialInfo>} [$$source = {}] - The source object to create the CredentialInfo.
     */
    constructor($$source = {}) {
        if (!("platform" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("token" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["token"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CredentialInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CredentialInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CredentialInfo(/** @type {Partial<CredentialInfo>} */($$parsedSource));
    }
}

/**
 * FileInfo 文件信息
 */
export class FileInfo {
    /**
     * Creates a new FileInfo instance.
     * @param {Partial<FileInfo>} [$$source = {}] - The source object to create the FileInfo.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("statusText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["statusText"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("staged" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["staged"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileInfo(/** @type {Partial<FileInfo>} */($$parsedSource));
    }
}

/**
 * GitConfig Git 全局配置
 */
export class GitConfig {
    /**
     * Creates a new GitConfig instance.
     * @param {Partial<GitConfig>} [$$source = {}] - The source object to create the GitConfig.
     */
    constructor($$source = {}) {
        if (!("userName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userName"] = "";
        }
        if (!("userEmail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userEmail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitConfig(/** @type {Partial<GitConfig>} */($$parsedSource));
    }
}

/**
 * GitStatus Git 安装状态
 */
export class GitStatus {
    /**
     * Creates a new GitStatus instance.
     * @param {Partial<GitStatus>} [$$source = {}] - The source object to create the GitStatus.
     */
    constructor($$source = {}) {
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitStatus(/** @type {Partial<GitStatus>} */($$parsedSource));
    }
}

/**
 * MigrateOptions 迁移选项
 */
export class MigrateOptions {
    /**
     * Creates a new MigrateOptions instance.
     * @param {Partial<MigrateOptions>} [$$source = {}] - The source object to create the MigrateOptions.
     */
    constructor($$source = {}) {
        if (!("labels" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["labels"] = false;
        }
        if (!("issues" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["issues"] = false;
        }
        if (!("pullRequests" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["pullRequests"] = false;
        }
        if (!("releases" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["releases"] = false;
        }
        if (!("milestones" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["milestones"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MigrateOptions}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrateOptions(/** @type {Partial<MigrateOptions>} */($$parsedSource));
    }
}

/**
 * MigrateResult 迁移结果
 */
export class MigrateResult {
    /**
     * Creates a new MigrateResult instance.
     * @param {Partial<MigrateResult>} [$$source = {}] - The source object to create the MigrateResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cloneUrl"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["remoteName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MigrateResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MigrateResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MigrateResult(/** @type {Partial<MigrateResult>} */($$parsedSource));
    }
}

/**
 * OnlineMigrateCompareResult 在线迁移对比结果
 */
export class OnlineMigrateCompareResult {
    /**
     * Creates a new OnlineMigrateCompareResult instance.
     * @param {Partial<OnlineMigrateCompareResult>} [$$source = {}] - The source object to create the OnlineMigrateCompareResult.
     */
    constructor($$source = {}) {
        if (!("sourceRepos" in $$source)) {
            /**
             * 源平台所有仓库
             * @member
             * @type {RepoInfo[]}
             */
            this["sourceRepos"] = [];
        }
        if (!("targetRepos" in $$source)) {
            /**
             * 目标平台所有仓库
             * @member
             * @type {RepoInfo[]}
             */
            this["targetRepos"] = [];
        }
        if (!("missingRepos" in $$source)) {
            /**
             * 目标平台缺少的仓库
             * @member
             * @type {RepoInfo[]}
             */
            this["missingRepos"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnlineMigrateCompareResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OnlineMigrateCompareResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sourceRepos" in $$parsedSource) {
            $$parsedSource["sourceRepos"] = $$createField0_0($$parsedSource["sourceRepos"]);
        }
        if ("targetRepos" in $$parsedSource) {
            $$parsedSource["targetRepos"] = $$createField1_0($$parsedSource["targetRepos"]);
        }
        if ("missingRepos" in $$parsedSource) {
            $$parsedSource["missingRepos"] = $$createField2_0($$parsedSource["missingRepos"]);
        }
        return new OnlineMigrateCompareResult(/** @type {Partial<OnlineMigrateCompareResult>} */($$parsedSource));
    }
}

/**
 * OnlineMigrateItemResult 单个仓库在线迁移结果
 */
export class OnlineMigrateItemResult {
    /**
     * Creates a new OnlineMigrateItemResult instance.
     * @param {Partial<OnlineMigrateItemResult>} [$$source = {}] - The source object to create the OnlineMigrateItemResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cloneUrl"] = undefined;
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OnlineMigrateItemResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OnlineMigrateItemResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OnlineMigrateItemResult(/** @type {Partial<OnlineMigrateItemResult>} */($$parsedSource));
    }
}

/**
 * ProjectOverview 项目概览信息（轻量级）
 */
export class ProjectOverview {
    /**
     * Creates a new ProjectOverview instance.
     * @param {Partial<ProjectOverview>} [$$source = {}] - The source object to create the ProjectOverview.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("hasChanges" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasChanges"] = false;
        }
        if (!("unpushed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unpushed"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectOverview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectOverview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectOverview(/** @type {Partial<ProjectOverview>} */($$parsedSource));
    }
}

/**
 * ProjectStatus 项目状态信息
 */
export class ProjectStatus {
    /**
     * Creates a new ProjectStatus instance.
     * @param {Partial<ProjectStatus>} [$$source = {}] - The source object to create the ProjectStatus.
     */
    constructor($$source = {}) {
        if (!("branch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["branch"] = "";
        }
        if (!("remoteUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remoteUrl"] = "";
        }
        if (!("remotes" in $$source)) {
            /**
             * @member
             * @type {RemoteItem[]}
             */
            this["remotes"] = [];
        }
        if (!("currentRemote" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["currentRemote"] = "";
        }
        if (!("changedFiles" in $$source)) {
            /**
             * @member
             * @type {FileInfo[]}
             */
            this["changedFiles"] = [];
        }
        if (!("useProxy" in $$source)) {
            /**
             * nil=跟随全局, true=开启, false=关闭
             * @member
             * @type {boolean | null}
             */
            this["useProxy"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProjectStatus}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("remotes" in $$parsedSource) {
            $$parsedSource["remotes"] = $$createField2_0($$parsedSource["remotes"]);
        }
        if ("changedFiles" in $$parsedSource) {
            $$parsedSource["changedFiles"] = $$createField4_0($$parsedSource["changedFiles"]);
        }
        return new ProjectStatus(/** @type {Partial<ProjectStatus>} */($$parsedSource));
    }
}

/**
 * PushAllResult 一键多端推送结果
 */
export class PushAllResult {
    /**
     * Creates a new PushAllResult instance.
     * @param {Partial<PushAllResult>} [$$source = {}] - The source object to create the PushAllResult.
     */
    constructor($$source = {}) {
        if (!("remote" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["remote"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PushAllResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PushAllResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PushAllResult(/** @type {Partial<PushAllResult>} */($$parsedSource));
    }
}

/**
 * ReleaseInfo 通用 Release 信息
 */
export class ReleaseInfo {
    /**
     * Creates a new ReleaseInfo instance.
     * @param {Partial<ReleaseInfo>} [$$source = {}] - The source object to create the ReleaseInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("tagName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tagName"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("draft" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["draft"] = false;
        }
        if (!("prerelease" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["prerelease"] = false;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("publishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("assets" in $$source)) {
            /**
             * @member
             * @type {AssetInfo[]}
             */
            this["assets"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReleaseInfo}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("assets" in $$parsedSource) {
            $$parsedSource["assets"] = $$createField8_0($$parsedSource["assets"]);
        }
        return new ReleaseInfo(/** @type {Partial<ReleaseInfo>} */($$parsedSource));
    }
}

/**
 * ReleaseSyncResult 单条 Release 同步结果
 */
export class ReleaseSyncResult {
    /**
     * Creates a new ReleaseSyncResult instance.
     * @param {Partial<ReleaseSyncResult>} [$$source = {}] - The source object to create the ReleaseSyncResult.
     */
    constructor($$source = {}) {
        if (!("tagName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tagName"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseSyncResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ReleaseSyncResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseSyncResult(/** @type {Partial<ReleaseSyncResult>} */($$parsedSource));
    }
}

/**
 * RemoteItem 远程仓库信息
 */
export class RemoteItem {
    /**
     * Creates a new RemoteItem instance.
     * @param {Partial<RemoteItem>} [$$source = {}] - The source object to create the RemoteItem.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RemoteItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteItem(/** @type {Partial<RemoteItem>} */($$parsedSource));
    }
}

/**
 * RepoInfo 仓库信息
 */
export class RepoInfo {
    /**
     * Creates a new RepoInfo instance.
     * @param {Partial<RepoInfo>} [$$source = {}] - The source object to create the RepoInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("fullName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fullName"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("cloneUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["cloneUrl"] = "";
        }
        if (!("sshUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sshUrl"] = "";
        }
        if (!("private" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["private"] = false;
        }
        if (!("fork" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fork"] = false;
        }
        if (!("empty" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["empty"] = false;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RepoInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoInfo(/** @type {Partial<RepoInfo>} */($$parsedSource));
    }
}

/**
 * StashInfo 贮藏信息
 */
export class StashInfo {
    /**
     * Creates a new StashInfo instance.
     * @param {Partial<StashInfo>} [$$source = {}] - The source object to create the StashInfo.
     */
    constructor($$source = {}) {
        if (!("index" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["index"] = 0;
        }
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ref"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StashInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StashInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StashInfo(/** @type {Partial<StashInfo>} */($$parsedSource));
    }
}

/**
 * TagInfo 标签信息
 */
export class TagInfo {
    /**
     * Creates a new TagInfo instance.
     * @param {Partial<TagInfo>} [$$source = {}] - The source object to create the TagInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("hash" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hash"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timestamp"] = 0;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TagInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TagInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TagInfo(/** @type {Partial<TagInfo>} */($$parsedSource));
    }
}

/**
 * TreeNode 前端侧边栏树节点
 */
export class TreeNode {
    /**
     * Creates a new TreeNode instance.
     * @param {Partial<TreeNode>} [$$source = {}] - The source object to create the TreeNode.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * group, project
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TreeNode[] | undefined}
             */
            this["children"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TreeNode}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField5_0($$parsedSource["children"]);
        }
        return new TreeNode(/** @type {Partial<TreeNode>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = RepoInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RemoteItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = FileInfo.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = AssetInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = TreeNode.createFrom;
const $$createType9 = $Create.Array($$createType8);
